version: '3.8'

services:
  app:
    image: app/test
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    # environment:

    depends_on:
      - mysql
      - newrelic-daemon
    networks:
      - newrelic-php

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - newrelic-php
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - newrelic-php

  newrelic-daemon:
    image: newrelic/php-daemon
    container_name: newrelic-daemon
    restart: unless-stopped
    expose:
      - "31339"
    networks:
      - newrelic-php
volumes:
  db_data:
  trivy-cache:

networks:
  newrelic-php:
    external: true
  laravel:
