name: Code Scanning - PHP + JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  phpstan:
    name: PHPStan Laravel (Static Analysis)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, pdo, pdo_mysql
        tools: composer

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install PHPStan + Larastan
      run: composer require --dev phpstan/phpstan nunomaduro/larastan

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse app --level=5

  psalm:
    name: Run Psalm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, pdo, pdo_mysql
        tools: composer

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Psalm
      run: composer require --dev vimeo/psalm

    - name: Initialize Psalm (if needed)
      run: vendor/bin/psalm --init
      continue-on-error: true  # Skip error if already configured

    - name: Run Psalm analysis
      run: vendor/bin/psalm --alter --issues=MissingReturnType,UnusedVariable,MissingOverrideAttribute,ClassMustBeFinal,PossiblyUnusedMethod --dry-run
